
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package HOC2;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int NUM = 10;
  public static final int Asig = 6;
  public static final int ParDer = 8;
  public static final int UMINUS = 12;
  public static final int opProd = 4;
  public static final int opDiv = 5;
  public static final int Enter = 9;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int opResta = 3;
  public static final int error = 1;
  public static final int opSuma = 2;
  public static final int ParIzq = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "opSuma",
  "opResta",
  "opProd",
  "opDiv",
  "Asig",
  "ParIzq",
  "ParDer",
  "Enter",
  "NUM",
  "VAR",
  "UMINUS"
  };
}

